In [2]:
import numpy as np
import torch
import SimpleITK as sitk

In [3]:
niiobj = sitk.GetArrayFromImage(sitk.ReadImage(
    "/home/yeep/project/py/ALSph2d/data/val/image/201404260019_t1_fs_tse_rs_tra_0_0_0_axial_20140429.nii.gz"))

In [6]:
niiobj = (niiobj - niiobj.mean()) / niiobj.std()

In [12]:
niiobj.shape

(35, 640, 640)

In [44]:
mean = torch.mean(torch.tensor(niiobj), (1, 2))
std = torch.std(torch.tensor(niiobj), (1, 2))

In [45]:
(torch.from_numpy(niiobj) - mean) / std

RuntimeError: The size of tensor a (640) must match the size of tensor b (35) at non-singleton dimension 2

In [48]:
torchnii = torch.from_numpy(niiobj)

In [50]:
torchnii - mean

RuntimeError: The size of tensor a (640) must match the size of tensor b (35) at non-singleton dimension 2

In [56]:
a = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
a.log_softmax(dim=0)

tensor([-3.4402, -2.4402, -1.4402, -0.4402])

In [57]:
a = torch.randn(15, 2, 8, 8)
b = a.log_softmax(dim=1)

In [63]:
a = torch.randn(5)
b = torch.randn(4, 3)

In [64]:
torch.matmul(a, b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x5 and 4x3)

In [71]:
import numpy as np

a = torch.randn(16, 2, 10, 10).softmax(dim=1)
spacing32 = np.spacing(1, dtype=np.float32)

In [126]:
torch.abs(a[:, 0] - a[:, 1]).mean(dim=[-2, -1]).shape

torch.Size([16])

In [99]:
torch.mean(-a * torch.log(1e-12 + a), dim=[1, 2, 3]) * 2

tensor([0.5532, 0.5594, 0.5131, 0.5266, 0.5661, 0.5298, 0.5426, 0.5494, 0.5452,
        0.5304, 0.5325, 0.5255, 0.5337, 0.5515, 0.5553, 0.5398])

In [106]:
out = torch.mean(-a * torch.log(a + 1e-12), dim=[1, 2, 3]) * 2

In [113]:
torch.column_stack([torch.arange(0, a.shape[0], dtype=torch.int), out]).data

tensor([[ 0.0000,  0.5532],
        [ 1.0000,  0.5594],
        [ 2.0000,  0.5131],
        [ 3.0000,  0.5266],
        [ 4.0000,  0.5661],
        [ 5.0000,  0.5298],
        [ 6.0000,  0.5426],
        [ 7.0000,  0.5494],
        [ 8.0000,  0.5452],
        [ 9.0000,  0.5304],
        [10.0000,  0.5325],
        [11.0000,  0.5255],
        [12.0000,  0.5337],
        [13.0000,  0.5515],
        [14.0000,  0.5553],
        [15.0000,  0.5398]])

In [97]:
def cal_entropy_score(probs):  # C,H,W  熵越大，越难分
    batch_scores = []
    for i in range(len(probs)):  # prob img
        entropy = np.mean(-np.nansum(np.multiply(probs[i], np.log(probs[i] + 1e-12)), axis=0))  # 表示沿着第1维计算
        batch_scores.append(entropy)
    return batch_scores

In [101]:
a.log()

tensor([[[[-0.2561, -0.6062, -1.2486,  ..., -1.2746, -0.4427, -0.1826],
          [-1.1516, -1.4491, -0.7113,  ..., -0.1433, -0.5624, -1.6300],
          [-0.1890, -0.3224, -0.3352,  ..., -2.0540, -0.5882, -0.3552],
          ...,
          [-0.9154, -0.2701, -0.9762,  ..., -0.5006, -0.7071, -3.2098],
          [-1.1479, -1.0374, -1.3309,  ..., -1.7035, -0.6645, -0.6043],
          [-2.4275, -0.2842, -0.6278,  ..., -0.8470, -2.6765, -0.2615]],

         [[-1.4874, -0.7883, -0.3381,  ..., -0.3279, -1.0280, -1.7902],
          [-0.3800, -0.2676, -0.6753,  ..., -2.0133, -0.8436, -0.2181],
          [-1.7590, -1.2889, -1.2559,  ..., -0.1372, -0.8105, -1.2074],
          ...,
          [-0.5114, -1.4409, -0.4728,  ..., -0.9318, -0.6794, -0.0412],
          [-0.3817, -0.4375, -0.3069,  ..., -0.2009, -0.7226, -0.7906],
          [-0.0924, -1.3968, -0.7630,  ..., -0.5598, -0.0713, -1.4691]]],


        [[[-0.4371, -0.3187, -0.9916,  ..., -0.4332, -0.4896, -1.3280],
          [-0.4556, -0.0748,

In [4]:
import torch.nn as nn
import torch

In [5]:
a = nn.Dropout()

In [8]:
a(torch.ones(16, 8, 8))

tensor([[[0., 2., 2.,  ..., 2., 0., 2.],
         [2., 0., 0.,  ..., 0., 2., 2.],
         [2., 0., 2.,  ..., 2., 2., 2.],
         ...,
         [2., 0., 0.,  ..., 0., 2., 2.],
         [2., 2., 0.,  ..., 0., 2., 0.],
         [2., 2., 0.,  ..., 2., 2., 0.]],

        [[2., 0., 2.,  ..., 0., 0., 2.],
         [2., 2., 0.,  ..., 2., 2., 0.],
         [0., 0., 2.,  ..., 2., 0., 0.],
         ...,
         [0., 0., 2.,  ..., 0., 2., 0.],
         [0., 0., 2.,  ..., 0., 0., 0.],
         [0., 2., 0.,  ..., 2., 0., 2.]],

        [[2., 2., 0.,  ..., 0., 2., 2.],
         [2., 2., 0.,  ..., 0., 2., 2.],
         [2., 2., 0.,  ..., 2., 0., 0.],
         ...,
         [2., 0., 0.,  ..., 0., 2., 0.],
         [0., 2., 2.,  ..., 0., 2., 0.],
         [0., 2., 0.,  ..., 2., 0., 2.]],

        ...,

        [[2., 2., 2.,  ..., 0., 0., 2.],
         [0., 0., 0.,  ..., 0., 2., 0.],
         [2., 2., 2.,  ..., 2., 2., 2.],
         ...,
         [0., 2., 0.,  ..., 2., 2., 0.],
         [0., 2., 2., 

In [29]:
import torch
import numpy as np

In [30]:
a = torch.randn(1, 16, 16)
b = torch.randn(1, 16, 16)

In [31]:
torch.concat([a, b]).shape

torch.Size([2, 16, 16])

In [32]:
torch.stack([a, b]).shape

torch.Size([2, 1, 16, 16])

In [49]:
data = torch.randn(10, 16, 2, 10, 10)

In [50]:
data

tensor([[[[[-4.8334e-01, -1.4555e+00, -3.4388e-01,  ...,  2.1974e-01,
             5.1325e-01,  1.6290e-01],
           [ 6.2118e-01,  3.9054e-01,  6.3982e-01,  ...,  3.8063e-01,
            -5.0744e-01,  1.2305e+00],
           [-5.7083e-01, -1.3409e-02, -5.4603e-01,  ..., -3.1158e-01,
            -1.6503e+00, -8.3915e-01],
           ...,
           [-8.0001e-01, -5.0149e-01,  9.3452e-02,  ..., -1.8166e+00,
            -3.3981e-01, -5.4315e-01],
           [ 2.3842e-01,  8.6278e-01,  8.5218e-01,  ...,  9.1509e-01,
            -1.3137e-01, -1.0346e+00],
           [ 4.9777e-01,  3.4040e-01,  3.7302e-01,  ..., -4.5129e-01,
             3.7988e-01,  6.3454e-02]],

          [[ 3.4251e-02,  1.2985e-01,  1.2217e+00,  ...,  6.1570e-01,
            -8.0567e-02,  3.2923e-01],
           [ 6.6053e-01,  4.2268e-01,  3.4507e-02,  ...,  1.4240e+00,
            -3.1264e-01,  1.3622e+00],
           [-1.3195e+00, -2.2647e-01, -6.3536e-01,  ..., -4.6400e-03,
            -9.8024e-01,  6.4066e-02],
 

In [51]:
a.mean(0).shape

torch.Size([16, 16])

In [56]:
SPACING32 = np.spacing(1, dtype=np.float32)
SPACING32

1.1920929e-07

In [82]:
data = torch.randint(0,200,size=(10,16,2,10,10),dtype=torch.float32).softmax(dim=2)

In [83]:
mean = data.mean(0)

In [84]:
mean_entropy = -torch.mean(mean * torch.log(mean + SPACING32), dim=[-3, -2, -1])

In [85]:
mean_entropy

tensor([0.3240, 0.3159, 0.3242, 0.3179, 0.3235, 0.3214, 0.3172, 0.3197, 0.3199,
        0.3201, 0.3238, 0.3195, 0.3187, 0.3185, 0.3208, 0.3143])

torch.Size([10, 16, 2, 10, 10])

In [87]:
torch.mean(torch.mean(-data * torch.log(data + SPACING32),dim=[-3,-2,-1]),dim=0)

tensor([0.0097, 0.0086, 0.0089, 0.0088, 0.0077, 0.0061, 0.0069, 0.0097, 0.0072,
        0.0069, 0.0071, 0.0062, 0.0072, 0.0088, 0.0090, 0.0069])

In [88]:
torch.mean(-data * torch.log(data + SPACING32),dim=[0,-3,-2,-1])

tensor([0.0097, 0.0086, 0.0089, 0.0088, 0.0077, 0.0061, 0.0069, 0.0097, 0.0072,
        0.0069, 0.0071, 0.0062, 0.0072, 0.0088, 0.0090, 0.0069])

In [31]:
import torchvision.transforms as T

In [32]:
class AddGaussianNoise(object):
    def __init__(self, mean=0., std=1.):
        self.std = std
        self.mean = mean

    def __call__(self, tensor):
        tensor = tensor.detach().cpu()
        noise = torch.randn(tensor.size())
        return tensor + noise * self.std + self.mean

    def __repr__(self):
        return self.__class__.__name__ + '(mean={0}, std={1})'.format(self.mean, self.std)

In [33]:
def augment_data(img, flip=0, n_rotation=0, flip_axis=2, rot_axis0=2, rot_axis1=3, jitter=0, blur=1, mean_gaussian=0, std_gaussian=0):
    """
    We apply the given transformation (flip and rotation) on the input image
    :param flip: [0 or 1] flip applied as the initial transformation
    :param flip: [0, 1, 2, 3] number of rotations applied as the initial transformation
    :param jitter:  (same) value for amount of brightness, contrast, saturation and hue jitter.
                    The factor will be uniformly from [max(0, 1 - value), 1 + value],
                    except for hue value which will be chosen between  0.5 < =[-value, value] <= 0.5
    :param blur: (same) value of kernel size and sigma for Gaussian blur. Kernel will have shape (value, value)
                 Sigma will be chosen uniformly at random between 0.1 and that value.
    """
    if flip != 0:
        img = torch.flip(img, [flip_axis])

    if n_rotation !=0:
        img = torch.rot90(img, n_rotation, [rot_axis0, rot_axis1])

    if jitter != 0:
        transform = T.ColorJitter(brightness=jitter, contrast=jitter, saturation=jitter, hue=jitter)
        img = transform(img)

    if blur != 1:
        transform = T.GaussianBlur(kernel_size=(blur,blur), sigma=(0.1, blur))
        img = transform(img)

    if mean_gaussian != 0 or std_gaussian != 0:
        transform = AddGaussianNoise(mean_gaussian, std_gaussian)
        img = transform(img)

    return img

In [67]:
import random

In [69]:

def random_augmentation(x, aug_dic=None, flip_axis=2, rotaxis0=2, rotaxis1=3,  aug_gaussian_mean=0,  aug_gaussian_std=0):
    """ We do augmentation (flip, rotation, mult(0.9 - 1.1)
    :param x: a tensor of shape (#channels, x, y) or (#channels, x, y, z)
    :param aug_dic: augmentation dictionary (if given)
    :param flip_axis: tensor axis for flipping
    :param rotaxis0: tensor first axis of rotation
    :param rotaxis1: tensor second axis of rotation
    :param type: type of input ('img' or 'target'). If 'target', no jitter or blurring will be applied
    """
    if aug_dic is None:
        # We get params for number of flips (0 or 1) and number of rotations (0 ro 3)
        flip = torch.randint(0, 2, (1,)).item() if random.random()>0.5 else 0
        num_rot = torch.randint(0, 4, (1,)).item() if random.random()>0.5 else 0

        # We define the same value for amount of brightness, contrast, saturation and hue jitter.
        # The factor will be uniformly from [max(0, 1 - value), 1 + value],
        # except for hue value which will be chosen between  0.5 < =[-value, value] <= 0.5
        jitter = 0.5 if random.random()>0.5 else 0

        # We define the same value for kernel size and max sigma.
        # Sigma will be chosen uniformly at random between (0.1, value)
        blur = 3 if random.random()>0.5 else 1

        mean_gaussian = aug_gaussian_mean if random.random()>0.5 else 0
        std_gaussian = aug_gaussian_std if random.random()>0.5 else 0

        aug_dic = {'flip': flip,
                    'rot': num_rot,
                    'jitter': jitter,
                    'blur': blur,
                    'mean_gaussian': mean_gaussian,
                    'std_gaussian': std_gaussian
                    }
    else:
        flip = aug_dic['flip']
        num_rot = aug_dic['rot']

        # If it is a target image, there will be no jitter and bluring transformation
        jitter = 0 if type == 'target' else aug_dic['jitter']
        blur = 1 if type == 'target' else aug_dic['blur']
        mean_gaussian = 0 if type == 'target' else aug_dic['mean_gaussian']
        std_gaussian = 0  if type == 'target' else aug_dic['std_gaussian']

    # We apply the transformations
    x_aug = augment_data(x, flip=flip, n_rotation=num_rot, flip_axis=flip_axis, rot_axis0=rotaxis0, rot_axis1=rotaxis1, jitter=jitter, blur=blur, mean_gaussian=mean_gaussian, std_gaussian=std_gaussian)

    return x_aug, aug_dic

In [70]:
def reverse_augment_data(img, flip=0, n_rotation=0, flip_axis=2, rot_axis0=2, rot_axis1=3):
    """
    We reverse the transformation (flip and rotation) of the given image
    :param flip: [0 or 1] flip applied as the initial transformation
    :param flip: [0, 1, 2, 3] number of rotations applied as the initial transformation
    """
    if n_rotation !=0:
        img = torch.rot90(img, 4 - n_rotation, [rot_axis0, rot_axis1])

    if flip != 0:
        img = torch.flip(img, [flip_axis])


    return img

In [71]:
import torch
import os
import numpy as np
from os.path import join, exists
import SimpleITK as sitk
from torch.utils.data import Dataset, SubsetRandomSampler
from PIL import Image
import albumentations as A

In [72]:
class Dataset2d(Dataset):
    def __init__(self, datafolder: str, transform=None) -> None:
        assert os.path.exists(datafolder), datafolder
        super().__init__()
        self.data_folder = datafolder
        self.transforms = transform
        assert exists(datafolder)
        assert exists((join(datafolder, "image")))
        self.jpg_data = os.listdir(os.path.join(datafolder, "image"))

    def __len__(self):
        return len(self.jpg_data)

    def __getitem__(self, index):
        data_name = label_name = self.jpg_data[index]
        data_path, label_path = join(self.data_folder, "image", data_name), join(self.data_folder, "label", label_name)
        data, label = Image.open(data_path).convert("L"), Image.open(label_path).convert("L")
        data, label = np.asarray(data, dtype=np.float32), np.asarray(label, dtype=np.uint8)
        data = (data - data.mean()) / data.std()
        if self.transforms is not None:
            transformed = self.transforms(image=data, mask=label)
            data, label = transformed["image"], transformed["mask"]

        return torch.tensor(data, dtype=torch.float32).unsqueeze(0), torch.tensor(label == 255,
                                                                                  dtype=torch.long).unsqueeze(0)

In [73]:
train_transform = A.Compose([A.PadIfNeeded(512, 512),A.CropNonEmptyMaskIfExists(416, 416, p=1)])
train_dataset = Dataset2d(datafolder=os.path.join("data", "train"),transform=train_transform)

In [74]:
dulabeled = torch.utils.data.DataLoader(train_dataset,
                                        batch_size=16,
                                        pin_memory=True,
                                        num_workers=0)

In [75]:
img,label = next(iter(dulabeled))

In [76]:
img.shape

torch.Size([16, 1, 416, 416])

In [77]:
aug_img = random_augmentation(img)

In [78]:
from torchvision.utils import  save_image

In [79]:
save_image(img,"1.jpg",normalize=True)
save_image(aug_img[0],"2.jpg",normalize=True)

In [80]:
aug_img[1]

{'flip': 0,
 'rot': 0,
 'jitter': 0,
 'blur': 1,
 'mean_gaussian': 0,
 'std_gaussian': 0}

In [81]:
random.random()

0.2661476411734959

In [82]:
import torch

In [84]:
a = torch.randn(1,10,requires_grad=True)

In [94]:
b = []
with torch.no_grad():
    c = a+1

In [95]:
c.grad_fn

In [98]:
d = c+2

In [97]:
d.grad_fn

In [100]:
a = [1,2,3,4,5]
sorted(a,reverse=True)

[5, 4, 3, 2, 1]